name: Update Contributing page

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    paths:
      - 'CONTRIBUTING.md'
    branches:
      - main

jobs:
  build:
    name: Build Contributing page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Script
        run: pnpm contributing:gen
